# Exclude some standard locations
exclude = [
    ".git",
    ".github",
    "build",
    "doc",
    "tests",
]

target-version = "py310"

[lint]
# Enable:
# pycodestyle ('E')
# pydocstyle ('D')
# pyflakes ('F')
# isort ('I')
# pyupgrade ('UP')
# numpy-specific ('NPY')
# ruff-specific ('RUF')
# flake8-blind-except ('BLE')
# flake8-comprehensions ('C4')
# flake8-return ('RET')
select = ["E", "D", "F", "I", "UP", "NPY", "RUF", "BLE", "C4", "RET"]
ignore = [
    "E501", # E501: line length violations. Enforce these with `black`
    "E741", # E741: Ambiguous variable name
    "D105", # D105: Missing docstring in magic method
    "D107", # D107: Missing docstring in init
    "D203", # D203: 1 blank line required before class docstring
    "D213", # D213: Multi-line docstring summary should start at the second line
    "D400", # D400: First line should end with a period (only ignoring this because there's another error that catches the same thing)
    "D401", # D401: First line should be in imperative mood
    "D407", # D407: Missing dashed underline after section
    "D413", # D413: Missing blank line after last section
    "NPY002", # NPY002: replace legacy numpy.random calls with np.random.Generator
]

[lint.per-file-ignores]
"*/__init__.py" = ["I", "F401", "F403"]
"caput/astro/constants.py" = ["F403", "F405"]
"caput/astro/coordinates/spherical.py" = ["F405"]

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "auto"
preview = false
quote-style = "double"
skip-magic-trailing-comma = false
