name: caput-ci-docs
on:
  pull_request:
    branches:
    - master
    - refactor-dev
  push:
    branches:
    - master

jobs:

  build-docs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev openmpi-bin libhdf5-serial-dev

    - name: Update pip
      run: pip install --upgrade pip

    # TODO: figure out to mock some of these packages so that we don't
    # have to install everything
    # editable install seems to be required to build api reference for
    # .pyx files, which are not included in a standard install
    - name: Install pip dependencies
      run: pip install --editable .[docs]

    - name: Build sphinx docs
      # NOTE: we would like to run with -W to turn warnings into errors,
      # but due to this issue: https://github.com/jbms/sphinx-immaterial/issues/140
      # we end up with warnings that can't be ignored using sphinx's
      # suppress_warnings option. So for now we just build the docs without -W.
      # run: SPHINXOPTS=-W make -C doc html
      run: make -C doc clean && make -C doc html
