name: caput-ci-linting
on:
  pull_request:
    branches:
    - master
    - refactor-dev
  push:
    branches:
    - master

jobs:
  
  lint-format-code-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Update pip
        run: pip install --upgrade pip

      - name: Install pip dependencies
        run: pip install ruff

      - name: Run ruff linter check
        run: ruff check .

      - name: Run ruff format check
        run: ruff format --check .
