name: caput-ci-tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  run-tests:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.13", "3.14"]
        editable-install: ["", "--editable"]
        exclude:
          # Just check the editable install once to make sure there
          # are no issues
          - python-version: "3.10"
            editable-install: "--editable"
          - python-version: "3.14"
            editable-install: "--editable"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install apt dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev openmpi-bin libhdf5-serial-dev

      - name: Install brew dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          CC=mpicc brew install open-mpi hdf5-mpi

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: pip install --upgrade pip

      - name: Disable OpenMP warning on macos
        if: matrix.os == 'macos-latest'
        run: echo "CAPUT_NO_OPENMP=1" >> "$GITHUB_ENV"

      - name: Disable zstd assembly for recent macos with missing wheel
        if: matrix.os == 'macos-latest' && matrix.python-version == '3.14'
        run: echo "CFLAGS=-DZSTD_DISABLE_ASM" >> "$GITHUB_ENV"

      - name: Install core package with MPI compiler
        run: CC=mpicc pip install ${{ matrix.editable-install }} ".[test]"

      - name: Run tests serial
        run: pytest .

      # TODO: figure out why this produces import errors on CI when
      # using a standard install, but works with editable install
      - name: Run doctests
        run: pytest --doctest-modules --ignore=./tests --doctest-continue-on-failure --doctest-ignore-import-errors .

      - name: Run tests parallel with a single process
        run: mpirun -np 1 pytest . --with-mpi

      - name: Run tests parallel with four processes
        run: mpirun --oversubscribe -np 4 pytest . --with-mpi
